# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    app.command.executor:
        class: AppBundle\Command\Executor
        arguments: ['@logger', '%app_command_executor_pretend%']

    app.wireless.scanner:
        class: AppBundle\Wireless\Scanner
        arguments: ['@logger', '@app.command.executor']
