# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    app.command.executor:
        class: AppBundle\Command\Executor
        arguments: ['@logger', '%app_command_executor_pretend%']

    app.network.preferred_interface:
        class: AppBundle\Network\NetworkInterface
        arguments: ['%app_preferred_network_interface%', '@app.command.executor']

    app.wireless.scanner:
        class: AppBundle\Wireless\Scanner\Scanner
        arguments: ['@app.network.preferred_interface', '@logger', '@app.command.executor', '%app_wireless_scanner_max_tries%']

    app.wireless.network_manager:
        class: AppBundle\Wireless\NetworkManager
        arguments: ['@app.network.preferred_interface', '%app_wpa_supplicant_config_file%', '@logger', '@app.command.executor']
